LABELS = [
    "Ice Cap",
    "Tundra",
    "Cold Taiga",
    "Cool Taiga",
    "Hemiboreal Continental",
    "Dry Summer Continental",
    "Humid Continental",
    "Humid Warm Temperate",
    "Cool West Coast",
    "Cool Oceanic",
    "Mild West Coast",
    "Mild Oceanic",
    "Mediterranean",
    "Humid Subtropical",
    "Variable Semi-Arid",
    "Moderated Semi-Arid",
    "Hot Semi-Arid",
    "Variable Desert",
    "Moderated Desert",
    "Hot Desert",
    "Tropical Monsoon Savanna",
    "Tropical Rainforest",
]

LEGEND_ITEMS = [
    ("Ice Cap", "#808080"),
    ("Tundra", "#C5C9C7"),
    ("Cold Taiga", "#22421C"),
    ("Cool Taiga", "#2C7AAB"),

    ("Hemiboreal Continental", "#487A40"),
    ("Dry Summer Continental", "#A863DB"),
    ("Humid Continental", "#90EE90"),
    ("Humid Warm Temperate", "#15B01A"),
    ("Cool West Coast", "#030764"),
    ("Cool Oceanic", "#84B07D"),
    ("Mild West Coast", "#BABF24"),
    ("Mild Oceanic", "#48E8B0"),
    ("Mediterranean", "#FFFF14"),
    ("Humid Subtropical", "#08FF26"),

    ("Variable Semi-Arid", "#BF9982"),
    ("Moderated Semi-Arid", "#784122"),
    ("Hot Semi-Arid", "#BD5615"),

    ("Variable Desert", "#FCE1C7"),
    ("Moderated Desert", "#FC74DA"),
    ("Hot Desert", "#FACC4B"),

    ("Tropical Monsoon Savanna", "#CDFC65"),
    ("Tropical Rainforest", "#1D7555"),
]

CBAR_LABELS = [
    "Ice Cap (A1)",
    "Tundra (A2)",
    "Cold Taiga (A3)",
    "Cool Taiga (A4)",
    "Hemiboreal Continental (Bw1)",
    "Dry Summer Continental (Bw2)",
    "Humid Continental (Bw3)",
    "Humid Warm Temperate (Bw4)",
    "Cool West Coast (Bw5)",
    "Cool Oceanic (Bw6)",
    "Mild West Coast (Bw7)",
    "Mild Oceanic (Bw8)",
    "Mediterranean (Bw9)",
    "Humid Subtropical (Bw10)",
    "Variable Semi-Arid (Bs)",
    "Moderated Semi-Arid (BCs1)",
    "Hot Semi-Arid (BCs2)",
    "Variable Desert (Bd)",
    "Moderated Desert (BCd1)",
    "Hot Desert (BCd2)",
    "Tropical Monsoon Savanna (Cw1)",
    "Tropical Rainforest (Cw2)",
]